var words = [ ["koń", "le cheval"],
  ["ja", "je"],
  ["ten", "ce"],
  ["i", "et"],
  ["że", "que"],
  ["nie", "ne"],
  ["tak", "oui"],
  ["robić", "faire"],
  ["kto, kogo", "qui"],
  ["wtedy, więc", "alors"],
  ["ale", "mais"],
  ["ona", "elle"],
  ["one", "elles"],
  ["w, do (podróże etc)", "en"],
  ["mówić", "dire"],
  ["tam", "y"],
  ["do, za", "pour"],
  ["w (konkretne miejsce)", "dans"],
  ["ja się myję", "je me lave"],
  ["on się myje", "il se lave"],
  ["iść", "aller"],
  ["dobrze", "bien"],
  ["ty", "tu"],
  ["jak, w jaki sposób", "comme"],
  ["widzieć", "voir"],
  ["wiedzieć, umieć", "savoir"],
  ["my", "nous"],
  ["następnie", "puis"],
  ["mój, moja, moje", "mon, ma, mes"],
  ["'ja' akcentowane", "moi"],
  ["każdy", "chaque"],
  ["czego", "que"],
  ["umieć, móc", "pouvoir"],
  ["ponieważ", "parce que"],
  ["z czymś", "avec"],
  ["wreszcie", "enfin"],
  ["trzeba", "il faut"],
  ["przez", "par"],
  ["kiedy", "quand"],
  ["chcieć", "vouloir"],
  ["mały", "petit"],
  ["więcej", "plus"],
  ["na, na czymś", "sur"],
  ["lub", "ou"],
  ["inny, drugi, odmienny", "autre"],
  ["dwa", "deux"],
  ["przyjść, przyjechać", "venir"],
  ["brać", "prendre"],
  ["wszyscy", "tout le monde"],
  ["przyjechać", "arriver"],
  ["dużo", "beaucoup de"],
  ["wierzyć", "croire"],
  ["godzina", "une heure"],
  ["nic", "rien"],
  ["dzień", "un jour"],
  ["położyć", "mettre"]
];
